### ISSUE TITLE
Setup Cosmos DB

### ISSUE THREAD

**Issue by eliassal** [bmaluijb/BuildingCloudNativeSolutions#1]
Hi Barry in the video you indicate that there is 3 branches, one for creating the cosmosDB which I can't find, I only see Master, withFunction, with asp, no branch for cosmos, can you please share instructions on how to create and populate the cosmos DBs, in order to continue with model "building-azure-cosmos-db-apps-with-visual-studio-slides"

I am using a locak CosmosDb container which I can access, and managed to create a CookiesDatabase, then I updated the appsetting in the mvc project

>  "CosmosDBEndpoint": "https://172.22.194.61:8081/",
>   "CosmosDBAccessKey": "mykey--------+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZ.....",
> 
but did not fill the other params
Here is copy of my local cosmos and the CookiesDatabase I created
![cookies_003](https://user-images.githubusercontent.com/8447864/87454534-6121df00-c604-11ea-8b03-9a150648db42.jpg)

I fired the mvc project and ran it, I got a nice page with 1 cookie as you can notice but no collections were created was created my cosmos DB 
![cookies](https://user-images.githubusercontent.com/8447864/87454569-73038200-c604-11ea-931a-7c4b314013aa.jpg)

Clicking on cookies, generates an error in the function

![cookies_002](https://user-images.githubusercontent.com/8447864/87454601-7e56ad80-c604-11ea-987d-8b5858c57bd8.jpg)

Thanks in advance

**Comment by bmaluijb** [comment]
Hi! The main branch is the one that creates the Cosmos DB and fills it with a collection and documents. All of this happens in CosmosDBConnector.cs. Can you check that you use the master branch and that it generates a database and collection? It should also call the method to initialize the data in the retrieveallcookies method, perhaps you can debug that.

**Comment by eliassal** [comment]
I did git clone after clicking on copy and It was on the master branch.
Yes, I have CosmosDBConnector.cs in NationalCookies.Data, I can see the sub

```
 private void InitializeCookies()
        {
            //define the cookie objects
            Cookie cookieChololateChip = new Cookie
            {
                Id = Guid.NewGuid(),
                ImageUrl = "https://intcookie.azureedge.net/cdn/cookie-cc.jpg",
                Name = "Chololate Chip",
                Price = 1.2
            };

            Cookie cookieButterCookie = new Cookie
            {
                Id = Guid.NewGuid(),
                ImageUrl = "https://intcookie.azureedge.net/cdn/cookie-bc.jpg",
                Name = "Butter Cookie",
                Price = 1.0
            };

            Cookie cookieMacaroon = new Cookie
            {
                Id = Guid.NewGuid(),
                ImageUrl = "https://intcookie.azureedge.net/cdn/cookie-mc.jpg",
                Name = "Macaroons",
                Price = 0.9
            };

            //add cookies to Cosmos DB
            CreateDocument(this._cookieCollectionName, cookieChololateChip);
            CreateDocument(this._cookieCollectionName, cookieButterCookie);
            CreateDocument(this._cookieCollectionName, cookieMacaroon);
        }
```

**Comment by bmaluijb** [comment]
So is it working now?

**Comment by eliassal** [comment]
No, I tried debugging, getting more details on the same finction, I think the error is saying that there is nothing in the DB

![cookies_004](https://user-images.githubusercontent.com/8447864/87458562-769a0780-c60a-11ea-8210-072b866fa13f.jpg)

**Comment by eliassal** [comment]
While debugging, all code inside the constructor CosmosDBConnector executed  but again inside the fucntion
`RetrieveAllCookies`
that it fails

**Comment by bmaluijb** [comment]
Mmm, it looks like it is expecting a collection, which isn’t there. Could you throw away the database in Cosmos DB and debug the code in the constructor that creates the database and collection and see if it actually creates a collection

**Comment by eliassal** [comment]
Ok I will drop it but should I remove it from appsettings as well the name of the DB?

**Comment by bmaluijb** [comment]
No, leave the settings

**Comment by eliassal** [comment]
OK, it created the database but not the collections nor inserted the cookies, what should I eneter for the 2 params 
```
 "CosmosDBCookieCollectionName": "",
  "CosmosDBOrderCollectionName": "",
```

**Comment by bmaluijb** [comment]
Ah, that might be it. Please fill in all values that the app settings file requires. Fill in whatever you like

**Comment by eliassal** [comment]
I entered cookies for the 1st one and orders for the 2nd, yes it created the collections and added the 3 cookies
Thanks for your help
